# Generated by Django 2.2.7 on 2019-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUUtilizeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('receipt_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
