# Generated by Django 2.2.7 on 2019-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpuutilize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuutilizedata',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
